export const modules = [
    "projects",
    "tickets",
    "invoices",
    "estimates",
    "events",
    "messages",
    "tasks",
    "timelogs",
    "contracts",
    "notices",
    "payments",
    "orders",
    "knowledgebase",
    "clients",
    "employees",
    "attendance",
    "expenses",
    "leaves",
    "leads",
    "holidays",
    "products",
    "reports",
    "settings",
    "bankaccount",
    "developers",
    "developer_projects",
    "partner_network",
    "offers",
    "properties",
] as const;
export const permissions = {
    "add_appreciation": "all",
    "add_attendance": "all",
    "add_bank_deposit": "all",
    "add_bank_transfer": "all",
    "add_bank_withdraw": "all",
    "add_bankaccount": "all",
    "add_client_contacts": "all",
    "add_client_document": "all",
    "add_client_note": "all",
    "add_clients": "all",
    "add_contract": "all",
    "add_contract_discussion": "all",
    "add_contract_files": "all",
    "add_deal_note": "all",
    "add_deal_pipeline": "all",
    "add_deals": "all",
    "add_department": "all",
    "add_designation": "all",
    "add_developer_projects": "all",
    "add_developers": "all",
    "add_documents": "all",
    "add_employees": "all",
    "add_estimate_request": "all",
    "add_estimates": "all",
    "add_events": "all",
    "add_expenses": "all",
    "add_holiday": "all",
    "add_immigration": "all",
    "add_invoices": "all",
    "add_knowledgebase": "all",
    "add_lead": "all",
    "add_lead_agent": "all",
    "add_lead_category": "all",
    "add_lead_files": "all",
    "add_lead_follow_up": "all",
    "add_lead_note": "all",
    "add_lead_proposals": "all",
    "add_lead_sources": "all",
    "add_leave": "all",
    "add_notice": "all",
    "add_order": "all",
    "add_payments": "all",
    "add_product": "all",
    "add_project_discussions": "all",
    "add_project_files": "all",
    "add_project_members": "all",
    "add_project_milestones": "all",
    "add_project_note": "all",
    "add_project_rating": "all",
    "add_projects": "all",
    "add_status": "all",
    "add_sub_tasks": "all",
    "add_task_category": "all",
    "add_task_comments": "all",
    "add_task_files": "all",
    "add_task_notes": "all",
    "add_tasks": "all",
    "add_tickets": "all",
    "add_timelogs": "all",
    "approve_expenses": "all",
    "approve_or_reject_leaves": "all",
    "approve_timelogs": "all",
    "change_deal_stages": "all",
    "change_employee_role": "all",
    "change_status": "all",
    "create_public_project": "all",
    "create_unassigned_tasks": "all",
    "delete_appreciation": "all",
    "delete_approve_leaves": "all",
    "delete_attendance": "all",
    "delete_bankaccount": "all",
    "delete_client_contacts": "all",
    "delete_client_document": "all",
    "delete_client_note": "all",
    "delete_clients": "all",
    "delete_contract": "all",
    "delete_contract_discussion": "all",
    "delete_contract_files": "all",
    "delete_deal_note": "all",
    "delete_deal_pipeline": "all",
    "delete_deals": "all",
    "delete_department": "all",
    "delete_designation": "all",
    "delete_developer_projects": "all",
    "delete_developers": "all",
    "delete_documents": "all",
    "delete_employees": "all",
    "delete_estimate_request": "all",
    "delete_estimates": "all",
    "delete_events": "all",
    "delete_expenses": "all",
    "delete_holiday": "all",
    "delete_immigration": "all",
    "delete_invoices": "all",
    "delete_knowledgebase": "all",
    "delete_lead": "all",
    "delete_lead_agent": "all",
    "delete_lead_category": "all",
    "delete_lead_files": "all",
    "delete_lead_follow_up": "all",
    "delete_lead_note": "all",
    "delete_lead_proposals": "all",
    "delete_lead_sources": "all",
    "delete_leave": "all",
    "delete_notice": "all",
    "delete_order": "all",
    "delete_payments": "all",
    "delete_product": "all",
    "delete_project_discussions": "all",
    "delete_project_files": "all",
    "delete_project_members": "all",
    "delete_project_milestones": "all",
    "delete_project_note": "all",
    "delete_project_rating": "all",
    "delete_projects": "all",
    "delete_sub_tasks": "all",
    "delete_task_category": "all",
    "delete_task_comments": "all",
    "delete_task_files": "all",
    "delete_task_notes": "all",
    "delete_tasks": "all",
    "delete_tickets": "all",
    "delete_timelogs": "all",
    "edit_appreciation": "all",
    "edit_attendance": "all",
    "edit_bankaccount": "all",
    "edit_client_contacts": "all",
    "edit_client_document": "all",
    "edit_client_note": "all",
    "edit_clients": "all",
    "edit_contract": "all",
    "edit_contract_discussion": "all",
    "edit_deal_note": "all",
    "edit_deal_pipeline": "all",
    "edit_deals": "all",
    "edit_department": "all",
    "edit_designation": "all",
    "edit_developer_projects": "all",
    "edit_developers": "all",
    "edit_documents": "all",
    "edit_employees": "all",
    "edit_estimate_request": "all",
    "edit_estimates": "all",
    "edit_events": "all",
    "edit_expenses": "all",
    "edit_holiday": "all",
    "edit_immigration": "all",
    "edit_invoices": "all",
    "edit_knowledgebase": "all",
    "edit_lead": "all",
    "edit_lead_agent": "all",
    "edit_lead_category": "all",
    "edit_lead_follow_up": "all",
    "edit_lead_note": "all",
    "edit_lead_proposals": "all",
    "edit_lead_sources": "all",
    "edit_leave": "all",
    "edit_notice": "all",
    "edit_order": "all",
    "edit_payments": "all",
    "edit_product": "all",
    "manage_offers": "all",
    "manage_partner_network": "all",
    "manage_properties": "all",
    "manage_property_configuration": "all",
    "manage_property_publish_requests": "all",
    "edit_project_discussions": "all",
    "edit_project_members": "all",
    "edit_project_milestones": "all",
    "edit_project_note": "all",
    "edit_project_rating": "all",
    "edit_projects": "all",
    "edit_sub_tasks": "all",
    "edit_task_category": "all",
    "edit_task_comments": "all",
    "edit_task_notes": "all",
    "edit_tasks": "all",
    "edit_tickets": "all",
    "edit_timelogs": "all",
    "link_expense_bank_account": "all",
    "link_invoice_bank_account": "all",
    "link_payment_bank_account": "all",
    "manage_active_timelogs": "all",
    "manage_app_setting": "all",
    "manage_attendance_setting": "all",
    "manage_award": "all",
    "manage_client_category": "all",
    "manage_client_subcategory": "all",
    "manage_company_setting": "all",
    "manage_contract_setting": "all",
    "manage_contract_template": "all",
    "manage_contract_type": "all",
    "manage_currency_setting": "all",
    "manage_custom_field_setting": "all",
    "manage_custom_link_setting": "all",
    "manage_deal_stages": "all",
    "manage_discussion_category": "all",
    "manage_emergency_contact": "all",
    "manage_employee_shifts": "all",
    "manage_expense_category": "all",
    "manage_finance_setting": "all",
    "manage_gdpr_setting": "all",
    "manage_google_calendar_setting": "all",
    "manage_increment_promotion": "all",
    "manage_language_setting": "all",
    "manage_lead_custom_forms": "all",
    "manage_qualification_mapping": "all",
    "manage_lead_setting": "all",
    "manage_leave_setting": "all",
    "manage_message_setting": "all",
    "merge_lead": "all",
    "manage_module_setting": "all",
    "manage_notification_setting": "all",
    "manage_payment_setting": "all",
    "manage_product_category": "all",
    "manage_product_sub_category": "all",
    "manage_project_category": "all",
    "manage_project_setting": "all",
    "manage_project_template": "all",
    "manage_proposal_template": "all",
    "manage_recurring_event": "all",
    "manage_recurring_expense": "all",
    "manage_recurring_invoice": "all",
    "manage_recurring_task": "all",
    "manage_role_permission_setting": "all",
    "manage_security_setting": "all",
    "manage_social_login_setting": "all",
    "manage_storage_setting": "all",
    "manage_task_setting": "all",
    "manage_tax": "all",
    "manage_theme_setting": "all",
    "manage_ticket_agent": "all",
    "manage_ticket_channel": "all",
    "manage_ticket_groups": "all",
    "manage_ticket_setting": "all",
    "manage_ticket_tags": "all",
    "manage_ticket_type": "all",
    "manage_time_log_setting": "all",
    "reject_estimate_request": "all",
    "renew_contract": "all",
    "send_reminder": "all",
    "task_labels": "all",
    "update_leaves_quota": "all",
    "view_appreciation": "all",
    "view_attendance": "all",
    "view_attendance_report": "all",
    "view_bankaccount": "all",
    "view_client_contacts": "all",
    "view_client_dashboard": "all",
    "view_client_document": "all",
    "view_client_note": "all",
    "view_clients": "all",
    "view_contract": "all",
    "view_contract_discussion": "all",
    "view_contract_files": "all",
    "view_deal_note": "all",
    "view_deal_pipeline": "all",
    "view_deals": "all",
    "view_department": "all",
    "view_designation": "all",
    "view_developer_projects": "all",
    "view_developers": "all",
    "view_documents": "all",
    "view_employee_projects": "all",
    "view_employee_tasks": "all",
    "view_employee_timelogs": "all",
    "view_employees": "all",
    "view_estimate_request": "all",
    "view_estimates": "all",
    "view_events": "all",
    "view_expense_report": "all",
    "view_expenses": "all",
    "view_finance_dashboard": "all",
    "view_finance_report": "all",
    "view_holiday": "all",
    "view_hr_dashboard": "all",
    "view_immigration": "all",
    "view_income_expense_report": "all",
    "view_increment_promotion": "all",
    "view_invoices": "all",
    "view_knowledgebase": "all",
    "view_lead": "all",
    "view_lead_agents": "all",
    "view_lead_category": "all",
    "view_lead_files": "all",
    "view_lead_follow_up": "all",
    "view_lead_note": "all",
    "view_lead_proposals": "all",
    "view_lead_report": "all",
    "view_lead_sources": "all",
    "view_leave": "all",
    "view_leave_report": "all",
    "view_leaves_taken": "all",
    "view_miroboard": "all",
    "view_notice": "all",
    "view_order": "all",
    "view_overview_dashboard": "all",
    "view_payments": "all",
    "view_product": "all",
    "view_project_budget": "all",
    "view_project_burndown_chart": "all",
    "view_project_dashboard": "all",
    "view_project_discussions": "all",
    "view_project_estimates": "all",
    "view_project_expenses": "all",
    "view_project_files": "all",
    "view_project_gantt_chart": "all",
    "view_project_hourly_rates": "all",
    "view_project_invoices": "all",
    "view_project_members": "all",
    "view_project_milestones": "all",
    "view_project_note": "all",
    "view_project_orders": "all",
    "view_project_payments": "all",
    "view_project_rating": "all",
    "view_project_tasks": "all",
    "view_project_template": "all",
    "view_project_timelogs": "all",
    "view_projects": "all",
    "view_sales_report": "all",
    "view_shift_roster": "all",
    "view_sub_tasks": "all",
    "view_task_category": "all",
    "view_task_comments": "all",
    "view_task_files": "all",
    "view_task_notes": "all",
    "view_task_report": "all",
    "view_tasks": "all",
    "view_ticket_dashboard": "all",
    "view_tickets": "all",
    "view_time_log_report": "all",
    "view_timelog_earnings": "all",
    "view_timelogs": "all",
    "view_unassigned_tasks": "all"
} as const;

export type PermissionScope = "all" | "added" | "owned" | "both"| "none" | number;
export type PermissionKey = keyof typeof permissions;
export type AppPermission = Record<PermissionKey, PermissionScope>;
export type AppModule = typeof modules[number];
