export const DEAL_REDESIGN_TOKENS = {
    BG: "#f5f6f8",
    SURFACE: "#ffffff",
    SURFACE_2: "#f8f9fb",
    NAVY: "#16294d",
    BLUE: "#1a6bb5",
    BLUE_LIGHT: "#e8f1fb",
    BLUE_MID: "#b8d4f0",
    GREEN: "#177a5b",
    GREEN_LIGHT: "#e1f5ee",
    GREEN_MID: "#9fe1cb",
    AMBER: "#92400e",
    AMBER_SOFT: "#fff7ed",
    AMBER_BANNER: "#fef3c7",
    AMBER_MID: "#fed7aa",
    RED: "#b91c1c",
    RED_SOFT: "#fef2f2",
    RED_MID: "#fecaca",
    TEAL: "#0f766e",
    TEAL_SOFT: "#e6f7f5",
    TEAL_MID: "#99e2d8",
    GRAY: "#f5f6f8",
    GRAY_MID: "#e8eaed",
    GRAY_DARK: "#5b6472",
    GRAY_DARKER: "#374151",
    BORDER: "#e2e5ea",
    BORDER_SOFT: "#eef0f3",
    TEXT: "#1a1f2e",
    TEXT_MUTED: "#5b6472",
    TEXT_HINT: "#9ca3af",
    WHITE: "#ffffff",
} as const;

export const DEAL_REDESIGN_FONT_STACK =
    "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
