export {
    REDESIGN_TOKENS as DEAL_REDESIGN_TOKENS,
    REDESIGN_TYPE as DEAL_REDESIGN_TYPE,
    REDESIGN_RADIUS as DEAL_REDESIGN_RADIUS,
    REDESIGN_FONT_STACK as DEAL_REDESIGN_FONT_STACK,
} from "@/Components/Redesign/tokens";
