name: Deploy WorkSuite CRM to Production

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Staging Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGIN_SSH_PRIVATE_KEY }}
          script: |
            cd ~/hibarr-crm-staging
            git pull origin staging
            rsync -av --exclude 'public/user-uploads' --exclude 'public/favicon.ico' --exclude 'storage/app/modules_statuses.json' --exclude 'Modules' --exclude '.env' ~/hibarr-crm-staging/ /var/www/html
            cd /var/www/html
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run production
            php artisan migrate --force
            php artisan queue:restart

  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Main Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/hibarr-crm
            git pull origin main
            rsync -av --exclude 'public/user-uploads' --exclude 'public/favicon.ico' --exclude 'storage/app/modules_statuses.json' --exclude 'Modules' --exclude '.env' ~/hibarr-crm/ /var/www/html
            cd /var/www/html
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run production
            php artisan migrate --force
