name: Deploy WorkSuite CRM to Production or Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, zip, gd, bcmath, fileinfo 

      - name: Ensure bootstrap/cache exists
        run: |
          mkdir -p bootstrap/cache
          chmod -R 775 bootstrap/cache 

      - name: Install Composer dependencies
        run: composer install 

      - name: install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: npm install

      - name: Build NPM Assets
        run: npm run build

      - name: Sync files to production server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: '.'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/var/www/html/crm_update'
          

      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            php artisan migrate --force
            php artisan optimize


    # 👇 This step uploads the log file as an artifact
      - name: Upload NPM debug log artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/