name: Deploy WorkSuite CRM to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/hibarr-crm
            git pull origin main
            rsync -av --exclude 'public/user-uploads' --exclude 'storage/app/modules_statuses.json' --exclude 'Modules' --exclude '.env' ~/hibarr-crm/ /var/www/html
            cd /var/www/html
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run production
            php artisan migrate --force
            php artisan optimize
