name: Deploy WorkSuite CRM to Production

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Staging Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGIN_SSH_PRIVATE_KEY }}
          port: 2244
          script: |
            cd ~/hibarr-crm-staging
            # RESET repo safely
            git restore --staged .
            git restore .
            git clean -fd
            
            git pull origin staging

            # Sync files to server while excluding generated assets
            rsync -av \
              --exclude 'public/user-uploads' \
              --exclude 'public/favicon.ico' \
              --exclude 'storage/app/modules_statuses.json' \
              --exclude 'Modules' \
              --exclude '.env' \
              --exclude 'public/js' \
              --exclude 'public/css' \
              --exclude 'public/build' \
              --exclude 'public/mix-manifest.json' \
              ~/hibarr-crm-staging/ /var/www/html

            cd /var/www/html
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run production
            php artisan migrate --force
            php artisan queue:restart

  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Main Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST_2 }}
          username: ${{ secrets.REMOTE_USER_2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY_2 }}
          script: |
            cd ~/hibarr-crm
            # RESET repo safely
            git restore --staged .
            git restore .
            git clean -fd
            
            git pull origin main

            # Sync files to server while excluding generated assets
            rsync -av \
              --exclude 'public/user-uploads' \
              --exclude 'public/favicon.ico' \
              --exclude 'storage/app/modules_statuses.json' \
              --exclude 'Modules' \
              --exclude '.env' \
              --exclude 'public/js' \
              --exclude 'public/css' \
              --exclude 'public/build' \
              --exclude 'public/mix-manifest.json' \
              ~/hibarr-crm/ /var/www/html

            cd /var/www/html
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run production
            php artisan migrate --force
