name: Deploy WorkSuite CRM

on:
  push:
    branches: [main, staging]
  workflow_dispatch:

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-22.04

    steps:
      - name: Run deployment via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGIN_SSH_PRIVATE_KEY }}
          port: 2244
          script: |
            cd ~/hibarr-crm-staging
            make deploy-staging

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04

    steps:
      - name: Run deployment via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          script: |
            cd ~/hibarr-crm
            make deploy-production
